### ISSUE TITLE
请问确定了吗

### ISSUE THREAD

**Issue by NoOne-hub** [lphgit/PrintkStruct#1]
最近我也有这个需求,然后自己编写的不通用

**Comment by lphgit** [comment]
没有呢，一考虑到通用性就犯了难

**Comment by NoOne-hub** [comment]
我解决了,依赖于python一个库,可以解析结构体pyclibrary

li penghui <notifications@github.com> 于2020年4月26日周日 上午11:25写道：

> 没有呢，一考虑到通用性就犯了难
>
